openapi: 3.0.0
info:
  version: "1.0.0"
  title: 'example-service'
servers:
  - url: /api/v1
  - url: example-service/api/v1
paths:
  /addexample:
    x-router-controller: example1Controller
    post:
      operationId: addExample
      tags:
        - "template-service"
      description: "example-route"
      parameters:
        - $ref: '#/components/parameters/ExampleProp'
      requestBody:
        $ref: '#/components/requestBodies/ExampleBody'
      responses:
        200:
          $ref: '#/components/responses/ExampleSuccessResponse'
        400:
          $ref: '#/components/responses/ExampleBadResponse'
        500:
          $ref: '#/components/responses/ExampleBadResponse'

components:
  requestBodies:
    ExampleBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExampleBody'
            
  responses:
    ExampleSuccessResponse:
      description: "OK"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExampleResponse'
    ExampleBadResponse:
      description: "KO"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExampleResponse'

  parameters:
    ExampleProp:
      name: exampleProp
      description: example parameter
      in: header
      required: true
      schema:
        $ref: '#/components/schemas/ExampleProp'

  schemas:
    ExampleProp:
      type: string
      
    ExampleResponse:
      type: object

    ExampleBody:
      type: object

## edit with https://editor.swagger.io/